package com.shasan731.networkinvestigator.core.network
import kotlinx.coroutines.runBlocking
import okhttp3.mockwebserver.MockResponse
import okhttp3.mockwebserver.MockWebServer
import org.junit.Assert.*
import org.junit.Test
import java.util.concurrent.TimeUnit
class NetworkAnalysisTest {
    @Test fun `http inspector follows and reports redirect chain`() = runBlocking { val server = MockWebServer(); server.enqueue(MockResponse().setResponseCode(302).addHeader("Location", "/final")); server.enqueue(MockResponse().setResponseCode(200).addHeader("Content-Type", "application/json").addHeader("Content-Security-Policy", "default-src 'none'").setBody("{\"ok\":true}")); server.start(); try { val result = HttpInspector().execute(server.url("/start").toString()) as com.shasan731.networkinvestigator.core.model.DiagnosticResult.Success<com.shasan731.networkinvestigator.core.model.HttpObservation>; val data = result.data; assertEquals(200, data.statusCode); assertEquals(2, data.redirectChain.size) } finally { server.close() } }
    @Test fun `security header analysis is case insensitive`() { val missing = SecurityHeaderAnalyzer.missing(mapOf("STRICT-TRANSPORT-SECURITY" to "max-age=1", "Content-Security-Policy" to "default-src 'none'", "Cache-Control" to "no-store")); assertFalse(missing.contains("HSTS")); assertFalse(missing.contains("Frame protection")); assertFalse(missing.contains("Cache Control")) }
    @Test fun `advanced explicit http sends method query and body without persisting auth`() = runBlocking { val server = MockWebServer(); server.enqueue(MockResponse().setResponseCode(201).setBody("{\"saved\":true}")); server.start(); try { val result = AdvancedHttpInspector().execute(HttpRequestSpec(server.url("/items").toString(), HttpMethod.POST, queryParameters = mapOf("mode" to "test"), body = "{\"x\":1}", bodyKind = BodyKind.JSON, bearerToken = "top-secret")) as com.shasan731.networkinvestigator.core.model.DiagnosticResult.Success<DetailedHttpObservation>; assertEquals(201, result.data.statusCode); assertTrue(result.data.bodyPreview.contains("saved")); val request = server.takeRequest(); assertEquals("POST", request.method); assertTrue(request.path!!.contains("mode=test")); assertEquals("Bearer top-secret", request.getHeader("Authorization")) } finally { server.close() } }
    @Test fun `advanced inspector reports http errors and delayed json deterministically`() = runBlocking { val server = MockWebServer(); server.enqueue(MockResponse().setResponseCode(503).setBodyDelay(25, TimeUnit.MILLISECONDS).addHeader("Content-Type", "application/json").setBody("{\"error\":true}")); server.start(); try { val result = AdvancedHttpInspector().execute(HttpRequestSpec(server.url("/health").toString())) as com.shasan731.networkinvestigator.core.model.DiagnosticResult.Success<DetailedHttpObservation>; assertEquals(503, result.data.statusCode); assertTrue(result.data.bodyPreview.contains("error")); assertTrue(result.data.timing.totalMs >= 0) } finally { server.close() } }
    @Test fun `resolver comparison reports records and ttl changes`() { val a = listOf(DnsRecord("x", 1, 60, "1.1.1.1")); val b = listOf(DnsRecord("x", 1, 120, "1.1.1.1"), DnsRecord("x", 1, 60, "2.2.2.2")); val diff = ResolverComparator.compare(a, b); assertEquals(setOf("1:2.2.2.2"), diff.added); assertEquals(setOf("1:1.1.1"), diff.ttlChanged) }
    @Test fun `tls expiration and wildcard matching are conservative`() { assertEquals(2L, TlsPolicy.daysUntilExpiration(3 * 86_400_000L, 86_400_000L)); assertTrue(TlsPolicy.hostnameMatches("api.example.com", "*.example.com")); assertFalse(TlsPolicy.hostnameMatches("deep.api.example.com", "*.example.com")) }
    @Test fun `extracts html and open graph metadata`() { val metadata = HtmlMetadataParser.parse("<html><head><title> Test page </title><meta name=\"description\" content=\"Summary\"><meta property=\"og:title\" content=\"Shared title\"></head></html>"); assertEquals("Test page", metadata.title); assertEquals("Summary", metadata.description); assertEquals("Shared title", metadata.openGraphTitle) }
    @Test fun `parses deterministic dns a response`() { val bytes = byteArrayOf(0,1, -127, -128, 0,1, 0,1, 0,0, 0,0, 1,97, 0, 0,1, 0,1, -64,12, 0,1, 0,1, 0,0,0,60, 0,4, 1,2,3,4); val record = DnsResponseParser.parse(bytes).single(); assertEquals("1.2.3.4", record.value); assertEquals(60L, record.ttl) }
}
