package com.shasan731.networkinvestigator.core.database

import androidx.room.*

@Entity(indices = [Index(value = ["normalizedValue"], unique = true)])
data class TargetEntity(@PrimaryKey(autoGenerate = true) val id: Long = 0, val originalValue: String, val normalizedValue: String, val targetType: String, val createdAt: Long)

@Entity(foreignKeys = [ForeignKey(entity = TargetEntity::class, parentColumns = ["id"], childColumns = ["targetId"], onDelete = ForeignKey.CASCADE)], indices = [Index("targetId"), Index("startedAt")])
data class InvestigationEntity(@PrimaryKey val id: String, val targetId: Long, val profile: String, val startedAt: Long, val completedAt: Long?, val snapshotJson: String)

@Entity(foreignKeys = [ForeignKey(entity = InvestigationEntity::class, parentColumns = ["id"], childColumns = ["investigationId"], onDelete = ForeignKey.CASCADE)], indices = [Index("investigationId")])
data class DiagnosticTaskEntity(@PrimaryKey(autoGenerate = true) val id: Long = 0, val investigationId: String, val taskType: String, val status: String, val source: String, val startedAt: Long, val durationMs: Long)

@Entity(foreignKeys = [ForeignKey(entity = InvestigationEntity::class, parentColumns = ["id"], childColumns = ["investigationId"], onDelete = ForeignKey.CASCADE)], indices = [Index("investigationId")]) data class DnsResultEntity(@PrimaryKey(autoGenerate = true) val id: Long = 0, val investigationId: String, val resolver: String, val recordsJson: String, val createdAt: Long)
@Entity(foreignKeys = [ForeignKey(entity = InvestigationEntity::class, parentColumns = ["id"], childColumns = ["investigationId"], onDelete = ForeignKey.CASCADE)], indices = [Index("investigationId")]) data class ReachabilityResultEntity(@PrimaryKey(autoGenerate = true) val id: Long = 0, val investigationId: String, val host: String, val port: Int?, val reachable: Boolean, val latencyMs: Long?)
@Entity(foreignKeys = [ForeignKey(entity = InvestigationEntity::class, parentColumns = ["id"], childColumns = ["investigationId"], onDelete = ForeignKey.CASCADE)], indices = [Index("investigationId")]) data class TracerouteResultEntity(@PrimaryKey(autoGenerate = true) val id: Long = 0, val investigationId: String, val hopsJson: String, val limitation: String?)
@Entity(foreignKeys = [ForeignKey(entity = InvestigationEntity::class, parentColumns = ["id"], childColumns = ["investigationId"], onDelete = ForeignKey.CASCADE)], indices = [Index("investigationId")]) data class HttpResultEntity(@PrimaryKey(autoGenerate = true) val id: Long = 0, val investigationId: String, val url: String, val statusCode: Int?, val headersJson: String, val bodyFilePath: String?)
@Entity(foreignKeys = [ForeignKey(entity = InvestigationEntity::class, parentColumns = ["id"], childColumns = ["investigationId"], onDelete = ForeignKey.CASCADE)], indices = [Index("investigationId")]) data class TlsResultEntity(@PrimaryKey(autoGenerate = true) val id: Long = 0, val investigationId: String, val host: String, val certificateJson: String, val fingerprintSha256: String?)
@Entity(foreignKeys = [ForeignKey(entity = InvestigationEntity::class, parentColumns = ["id"], childColumns = ["investigationId"], onDelete = ForeignKey.CASCADE)], indices = [Index("investigationId")]) data class PortResultEntity(@PrimaryKey(autoGenerate = true) val id: Long = 0, val investigationId: String, val host: String, val port: Int, val state: String, val latencyMs: Long?)
@Entity(indices = [Index(value = ["ipAddress"], unique = true), Index("lastSeen")]) data class LanDeviceEntity(@PrimaryKey(autoGenerate = true) val id: Long = 0, val ipAddress: String, val hostname: String?, val macAddress: String?, val userLabel: String?, val notes: String?, val category: String, val confidence: String, val firstSeen: Long, val lastSeen: Long)
@Entity(indices = [Index("measuredAt")]) data class WifiMeasurementEntity(@PrimaryKey(autoGenerate = true) val id: Long = 0, val label: String?, val ssid: String?, val bssid: String?, val rssi: Int?, val frequencyMhz: Int?, val linkSpeedMbps: Int?, val measuredAt: Long)
@Entity(indices = [Index("startedAt")]) data class ConnectivitySessionEntity(@PrimaryKey val id: String, val mode: String, val startedAt: Long, val completedAt: Long?, val label: String?)
@Entity(foreignKeys = [ForeignKey(entity = ConnectivitySessionEntity::class, parentColumns = ["id"], childColumns = ["sessionId"], onDelete = ForeignKey.CASCADE)], indices = [Index("sessionId"), Index("timestamp")]) data class ConnectivitySampleEntity(@PrimaryKey(autoGenerate = true) val id: Long = 0, val sessionId: String, val timestamp: Long, val transport: String?, val latencyMs: Long?, val packetLossPercent: Double?, val validated: Boolean?)
@Entity(indices = [Index("status"), Index("startedAt")]) data class IncidentEntity(@PrimaryKey val id: String, val title: String, val customerOrSite: String?, val target: String?, val problemDescription: String, val startedAt: Long, val resolvedAt: Long?, val status: String, val severity: String, val technicianNotes: String?, val probableCause: String?, val finalResolution: String?, val tagsJson: String, val networkType: String? = null, val deviceInformation: String? = null)
@Entity(primaryKeys = ["incidentId", "investigationId"], foreignKeys = [ForeignKey(entity = IncidentEntity::class, parentColumns = ["id"], childColumns = ["incidentId"], onDelete = ForeignKey.CASCADE), ForeignKey(entity = InvestigationEntity::class, parentColumns = ["id"], childColumns = ["investigationId"], onDelete = ForeignKey.CASCADE)], indices = [Index("investigationId")]) data class IncidentInvestigationCrossRef(val incidentId: String, val investigationId: String)
@Entity(foreignKeys = [ForeignKey(entity = IncidentEntity::class, parentColumns = ["id"], childColumns = ["incidentId"], onDelete = ForeignKey.CASCADE)], indices = [Index("incidentId")]) data class AttachmentEntity(@PrimaryKey(autoGenerate = true) val id: Long = 0, val incidentId: String, val displayName: String, val persistedUri: String, val mimeType: String, val addedAt: Long)
@Entity(indices = [Index("updatedAt")]) data class SavedRequestEntity(@PrimaryKey val id: String, val name: String, val method: String, val url: String, val headersJson: String, val bodyFilePath: String?, val updatedAt: Long)
@Entity(indices = [Index("expiresAt")]) data class ProviderCacheEntity(@PrimaryKey val cacheKey: String, val provider: String, val payloadJson: String, val createdAt: Long, val expiresAt: Long)
@Entity(foreignKeys = [ForeignKey(entity = TargetEntity::class, parentColumns = ["id"], childColumns = ["targetId"], onDelete = ForeignKey.CASCADE)], indices = [Index("targetId"), Index("updatedAt")]) data class UserNoteEntity(@PrimaryKey(autoGenerate = true) val id: Long = 0, val targetId: Long, val note: String, val updatedAt: Long)
